2020-02-26 23:23:35,859 INFO: Microblog startup [in D:/neusoft-python/ÍøÉÏÊÚ¿Î/flask¿ò¼Ü/microblog/microblog.py:13]
2020-02-26 23:47:11,972 INFO: Microblog startup [in D:/neusoft-python/ÍøÉÏÊÚ¿Î/flask¿ò¼Ü/microblog/microblog.py:13]
2020-02-27 14:38:49,159 INFO: Microblog startup [in D:/neusoft-python/ÍøÉÏÊÚ¿Î/flask¿ò¼Ü/microblog/microblog.py:13]
2020-02-27 15:04:29,570 INFO: Microblog startup [in D:/neusoft-python/ÍøÉÏÊÚ¿Î/flask¿ò¼Ü/microblog/microblog.py:13]
2020-02-27 15:05:04,106 ERROR: Exception on /index [GET] [in D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\routes.py", line 38, in index
    return render_template('index.html',title='home',posts=posts)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\templates\base.html", line 29, in top-level template code
    {% block content %}
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\templates\index.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-02-27 15:05:15,371 ERROR: Exception on /index [GET] [in D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\routes.py", line 38, in index
    return render_template('index.html',title='home',posts=posts)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\templates\base.html", line 29, in top-level template code
    {% block content %}
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\templates\index.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-02-27 15:05:41,400 ERROR: Exception on /index [GET] [in D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\routes.py", line 38, in index
    return render_template('index.html',title='home',posts=posts)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\templates\base.html", line 29, in top-level template code
    {% block content %}
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\templates\index.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-02-27 15:11:15,975 INFO: Microblog startup [in D:/neusoft-python/ÍøÉÏÊÚ¿Î/flask¿ò¼Ü/microblog/microblog.py:13]
