2020-02-27 15:47:55,689 ERROR: Exception on /index [GET] [in D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\routes.py", line 38, in index
    return render_template('index.html',title='home',form=form,posts=posts)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\templates\base.html", line 12, in template
    <a href="{{url_for('explore'}}">Explore</a>
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2020-02-27 15:48:47,659 INFO: Microblog startup [in D:/neusoft-python/ÍøÉÏÊÚ¿Î/flask¿ò¼Ü/microblog/microblog.py:13]
2020-02-27 15:51:01,927 INFO: Microblog startup [in D:/neusoft-python/ÍøÉÏÊÚ¿Î/flask¿ò¼Ü/microblog/microblog.py:13]
2020-02-27 16:00:08,715 INFO: Microblog startup [in D:/neusoft-python/ÍøÉÏÊÚ¿Î/flask¿ò¼Ü/microblog/microblog.py:13]
2020-02-27 16:42:34,738 INFO: Microblog startup [in D:/neusoft-python/ÍøÉÏÊÚ¿Î/flask¿ò¼Ü/microblog/microblog.py:13]
2020-02-27 16:42:46,887 ERROR: Exception on /user/mary [GET] [in D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\routes.py", line 92, in user
    return render_template('user.html',user=user,posts=posts.items,next_url=next_url, prev_url=prev_url)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\neusoft-python\ÍøÉÏÊÚ¿Î\flask¿ò¼Ü\microblog\app\templates\user.html", line 37, in template
    {% endblock%}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2020-02-27 16:44:00,315 INFO: Microblog startup [in D:/neusoft-python/ÍøÉÏÊÚ¿Î/flask¿ò¼Ü/microblog/microblog.py:13]
2020-02-27 16:47:04,640 INFO: Microblog startup [in D:/neusoft-python/ÍøÉÏÊÚ¿Î/flask¿ò¼Ü/microblog/microblog.py:13]
